### ISSUE TITLE
rulesets/cleancode.xml in phpmd.xml does not work.

### ISSUE THREAD

**Issue by paulKliemann** [mi-schi/phpmd-extension#1]
by adding the line `<rule ref="../../../../../../rulesets/cleancode.xml" />` to the phpmd.xml file, the tool breaks. if i remove this line from phpmd.xml everything works just fine. 

please fix <3

**Comment by mi-schi** [comment]
Hi,

which version do you use and what is the error message? In which environment breaks the tool? Local in one class or local by inspecting the code or in the jenkins integration?

**Comment by paulKliemann** [comment]
i updated to the latest stable version and now it works. seems like i was on an older version.
The error occurred locally in phpstorm.

works for me. thanks for your time anyways :) 
have a nice day!
