### ISSUE TITLE
PHP 7.4 support  

### ISSUE THREAD

**Issue by lisfox1** [mi-schi/phpmd-extension#10]
Using typed properties:
```
<?php
class User {
    public int $id;
    public string $name;
}
?>
```
Results in: 
`Try to avoid public class variables. Use Getter to access the variable. It supports the principle of privacy.`

**Comment by mi-schi** [comment]
Yes, is there a change?

**Comment by mi-schi** [comment]
If there is a new concept in PHP for public class members, please let me know and argument with sources. Thanks.
