### ISSUE TITLE
Remove composer.lock

### ISSUE THREAD

**Issue by lisfox1** [mi-schi/phpmd-extension#11]
At the moment the `phpmd/phpmd` package is stuck on the 2.10.1 version due to the composer lock being committed to the repository. Would it be possible to remove it or at least update it?
From my understanding the packages which are being distributed shouldn't have lock file committed and versions should be forced by composer.json

**Comment by mi-schi** [comment]
I can remove it if you want but why you close the request? Do you still need the change?

**Comment by lisfox1** [comment]
I closed the issue because I manage to go around this problem by adding the `phpmd/phpmd` to my own composer.json and then running an update on `phpmd/phpmd` and `mi-schi/phpmd-extension` in a single cmd.
`composer update 'phpmd/phpmd:2.12' mi-schi/phpmd-extension`

**Comment by mi-schi** [comment]
Okay, if you have any request feel free to write here :)
