### ISSUE TITLE
Reminder: Überdenken der returnStatement-Regel

### ISSUE THREAD

**Issue by paulKliemann** [mi-schi/phpmd-extension#3]
Zur Erinnerung hier fesgehalten. Überdenken der Sinnhaftigkeit von folgender Violation: 
_A return statement line should only contains Variable,MemberPrimaryPrefix,Literal,FunctionPostfix,Array,ArrayIndexExpression,CastExpression,AllocationExpression,CloneExpression. It increase the reading rate._

**Comment by mi-schi** [comment]
I've fixed the rule. The whitelist was converted to a blacklist for boolean and, or, unary.
Now it is possible to write instanceOf and logical operators in a return statement. I don't like it very much because you switch the type while returning.
