### ISSUE TITLE
SuppressWarnings for ControllerMethodName doesn't work if annotated above Method

### ISSUE THREAD

**Issue by paulKliemann** [mi-schi/phpmd-extension#4]
it does work when its annotated above the class, but that means it will be suppressed for all methods within the controller. i only want to supress the warnings for a few methods in the controller. Please take a look into this. Thank you.

**Comment by mi-schi** [comment]
Thank you for your notice. I change the ControllerMethodName rule type from a class rule to a method rule. So you can set the annotation to supress the warnings in the method doc block in the new stable or 4.1.2 version of phpmd-extension.
