### ISSUE TITLE
combine phpmd-extension and git hook

### ISSUE THREAD

**Issue by StephanKrauss** [mi-schi/phpmd-extension#7]
Hello,

great work.
Is there a way to combine phpmd-extension with a git hook ?
I will define same standards and looking for a git hook.
I will use 
https://github.com/edorian/php-coding-standard-generator
to define standards in the phpmd.xml.

Your sincerly

Stephan

**Comment by mi-schi** [comment]
Hello, yes it is possible. I search for a script.

**Comment by StephanKrauss** [comment]
Hello,

At the moment I'm testing the use of edorian / php-coding-standard-generator.


A simple example can be found at: http://standard.stephankrauss.de

I have a dream. I want to test the code quality with simple means. Both in PhpStorm with a plugin and in Git with a hook.

Greetings from Leipzig to Dresden.

Greeting Stephan

**Comment by mi-schi** [comment]
Hi,

you can inspirate here: https://github.com/tommy-muehle/php-hooks

A friend of mine recomment this tool:
https://github.com/phpro/grumphp

I hope it helps. I'm not similar with PHP since one year.
