### ISSUE TITLE
rule for testing phpdoc

### ISSUE THREAD

**Issue by StephanKrauss** [mi-schi/phpmd-extension#8]
Hi Michael,

I'm looking for a role for phpmd.
This role should identify if a script has been sufficiently documented.
I think that the number of lines of a file in the relation of the comment lines must be evaluated. Can you help with an idea?

Greeting Stephan

**Comment by mi-schi** [comment]
The only rule for commentsbin this repo is this on: https://github.com/mi-schi/phpmd-extension/blob/master/rulesets/naming.xml#L47-L50
Unseless comments

The structure of comments are defined in PHPCS:

https://github.com/squizlabs/PHP_CodeSniffer/tree/master/src/Standards/Squiz/Sniffs/Commenting
