### ISSUE TITLE
Controller Action Naming 

### ISSUE THREAD

**Issue by samnela** [mi-schi/phpmd-extension#9]
Don't add the Action suffix to the methods of the controller actions.This suffix became optional when annotations were introduced for controllers. In modern Symfony applications this suffix is neither required nor recommended .

**Comment by mi-schi** [comment]
Okay thanks for the information. I'll try to remove it.

Do you have a reference?

**Comment by mi-schi** [comment]
Okay, I find the reference: The "Action" suffix was removed in the documention for Symfony 4.0: https://symfony.com/doc/4.0/controller.html
In the documentation for Symfony 3.3 the "Action" suffix is defined: https://symfony.com/doc/3.3/controller.html

**Comment by mi-schi** [comment]
I create a new version 4.3.0

**Comment by samnela** [comment]
Sorry for the delay, my reference is Symfony best practices : http://symfony.com/doc/current/best_practices/controllers.html#controller-action-naming
thank you @mi-schi  for this one .

**Comment by mi-schi** [comment]
Thx. I created a new version yesterday :) Feel free to update ;)
